#!/bin/bash

# Required to pass build env vars to the dockerfile on docker hub
docker buildx create --name multiarch --use
docker buildx build --pull --provenance=true --sbom=true -t $IMAGE_NAME . --build-arg SOURCE_BRANCH=${SOURCE_BRANCH} --push
